"""
FileTemplate / CommandTemplate Registry (§32, §22).

결정론적 RemediationProposal 생성을 위한 템플릿 저장소.

- FileTemplate: ``base_content`` 에 ``{{var}}`` placeholder. Jinja2 미사용 (의도적
  단순화) — 단순 문자열 치환 + 인덱싱된 변수만 지원.
- CommandTemplate: ``command_pattern`` 에 같은 placeholder. 적용 시 ``executor``
  / ``command_safety`` 모듈이 검증한 뒤 실행.

본 모듈은 in-memory store (built-in 만). 외부 사용자 등록은 추후 (§32.5).
"""

from __future__ import annotations

import re
from typing import Optional

try:
    from schemas import (
        ActionType,
        ApprovalLevel,
        CommandTemplate,
        FileTemplate,
        FileType,
        RiskLevel,
    )
except ImportError:  # pragma: no cover
    from core.schemas import (  # type: ignore
        ActionType,
        ApprovalLevel,
        CommandTemplate,
        FileTemplate,
        FileType,
        RiskLevel,
    )


# ---------------------------------------------------------------------------
# Template substitution
# ---------------------------------------------------------------------------


_VAR_RE: re.Pattern[str] = re.compile(r"\{\{\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\}")


def render(template_body: str, variables: dict[str, object]) -> str:
    """``{{var}}`` 단순 치환. 누락된 변수는 KeyError.

    Jinja2 보다 단순한 의도된 미니 템플릿 — 결정론적, 의미 분기 없음.
    """
    def _repl(m: re.Match[str]) -> str:
        key = m.group(1)
        if key not in variables:
            raise KeyError(f"Template variable missing: {key}")
        return str(variables[key])
    return _VAR_RE.sub(_repl, template_body)


def required_variables(template_body: str) -> list[str]:
    """템플릿이 요구하는 변수 이름 목록 (중복 제거, 등장 순서)."""
    seen: dict[str, bool] = {}
    for m in _VAR_RE.finditer(template_body):
        seen[m.group(1)] = True
    return list(seen.keys())


# ---------------------------------------------------------------------------
# Built-in templates — 12 blocker codes 커버
# ---------------------------------------------------------------------------


_FILE_TEMPLATES: list[FileTemplate] = [
    FileTemplate(
        template_id="env.example.create",
        file_type=FileType.ENV_FILE,
        base_content=(
            "# Auto-generated by ReCoder Remediation (§32).\n"
            "# 실제 값을 채우고 .env 로 복사하세요.\n"
            "{{env_lines}}\n"
        ),
        customizable_sections={"env_lines": "환경 변수 placeholder 들"},
    ),
    FileTemplate(
        template_id="gitignore.env.append",
        file_type=FileType.GITIGNORE,
        base_content=(
            "\n# Added by ReCoder Remediation — .env files should never be committed\n"
            ".env\n"
            ".env.local\n"
            ".env.*.local\n"
        ),
    ),
    FileTemplate(
        template_id="dockerfile.fastapi",
        file_type=FileType.DOCKERFILE,
        base_content=(
            "# Generated by ReCoder Remediation (§32) — FastAPI stack\n"
            "FROM python:{{python_version}}-slim\n"
            "WORKDIR /app\n"
            "COPY requirements.txt /app/\n"
            "RUN pip install --no-cache-dir -r requirements.txt\n"
            "COPY ./app /app/app\n"
            "EXPOSE {{app_port}}\n"
            'CMD ["uvicorn", "{{module_path}}", "--host", "0.0.0.0", "--port", "{{app_port}}"]\n'
        ),
        customizable_sections={
            "python_version": "Python base image tag",
            "app_port": "App port (Contract.runtime.app_port)",
            "module_path": "uvicorn module path (e.g., app.main:app)",
        },
    ),
    FileTemplate(
        template_id="dockerfile.flask",
        file_type=FileType.DOCKERFILE,
        base_content=(
            "FROM python:{{python_version}}-slim\n"
            "WORKDIR /app\n"
            "COPY requirements.txt /app/\n"
            "RUN pip install --no-cache-dir -r requirements.txt\n"
            "COPY . /app\n"
            "EXPOSE {{app_port}}\n"
            'CMD ["gunicorn", "-b", "0.0.0.0:{{app_port}}", "{{module_path}}"]\n'
        ),
    ),
    FileTemplate(
        template_id="dockerfile.node",
        file_type=FileType.DOCKERFILE,
        base_content=(
            "FROM node:{{node_version}}-alpine\n"
            "WORKDIR /app\n"
            "COPY package*.json ./\n"
            "RUN npm ci --omit=dev\n"
            "COPY . .\n"
            "EXPOSE {{app_port}}\n"
            'CMD ["node", "{{entry_file}}"]\n'
        ),
    ),
    FileTemplate(
        template_id="health.fastapi.snippet",
        file_type=FileType.PYTHON_SOURCE,
        base_content=(
            "\n@app.get(\"/healthz\")\n"
            "def healthz():\n"
            "    \"\"\"Auto-added by ReCoder Remediation (§32) — health probe.\"\"\"\n"
            "    return {\"status\": \"ok\"}\n"
        ),
    ),
    FileTemplate(
        template_id="health.flask.snippet",
        file_type=FileType.PYTHON_SOURCE,
        base_content=(
            "\n@app.route(\"/healthz\")\n"
            "def healthz():\n"
            "    return {\"status\": \"ok\"}, 200\n"
        ),
    ),
    FileTemplate(
        template_id="health.express.snippet",
        file_type=FileType.JS_SOURCE,
        base_content=(
            "\napp.get('/healthz', (req, res) => res.json({ status: 'ok' }));\n"
        ),
    ),
    FileTemplate(
        template_id="dockerfile.expose.append",
        file_type=FileType.DOCKERFILE,
        base_content="EXPOSE {{app_port}}\n",
    ),
    FileTemplate(
        template_id="recoder.yml.port.update",
        file_type=FileType.OTHER,
        base_content="# RemediationProposal recoder.yml port update — apply_method=CONTRACT_UPDATE",
        customizable_sections={
            "host_port": "Contract.runtime.host_port 으로 변경할 값",
            "app_port": "Contract.runtime.app_port 으로 변경할 값",
        },
    ),
]


_COMMAND_TEMPLATES: list[CommandTemplate] = [
    CommandTemplate(
        template_id="port.kill.windows",
        action_type=ActionType.SYSTEM_COMMAND,
        allowed_params={"port": {"type": "int", "min": 1, "max": 65535}},
        command_pattern="for /f \"tokens=5\" %a in ('netstat -ano ^| findstr :{{port}}') do taskkill /PID %a /F",
        risk_level=RiskLevel.HIGH,
        approval_level=ApprovalLevel.DOUBLE_CONFIRM,
    ),
    CommandTemplate(
        template_id="port.kill.unix",
        action_type=ActionType.SYSTEM_COMMAND,
        allowed_params={"port": {"type": "int", "min": 1, "max": 65535}},
        command_pattern="kill -9 $(lsof -ti:{{port}})",
        risk_level=RiskLevel.HIGH,
        approval_level=ApprovalLevel.DOUBLE_CONFIRM,
    ),
    CommandTemplate(
        template_id="pip.compile.requirements",
        action_type=ActionType.PACKAGE_INSTALL,
        allowed_params={},
        command_pattern="pip-compile --generate-hashes requirements.in",
        risk_level=RiskLevel.LOW,
        approval_level=ApprovalLevel.CONFIRM,
    ),
    CommandTemplate(
        template_id="npm.audit.fix",
        action_type=ActionType.PACKAGE_INSTALL,
        allowed_params={},
        command_pattern="npm audit fix --omit=dev",
        risk_level=RiskLevel.MEDIUM,
        approval_level=ApprovalLevel.CONFIRM,
    ),
    CommandTemplate(
        template_id="pip.audit.run",
        action_type=ActionType.PACKAGE_INSTALL,
        allowed_params={},
        command_pattern="pip-audit --strict",
        risk_level=RiskLevel.LOW,
        approval_level=ApprovalLevel.AUTO,
    ),
]


# ---------------------------------------------------------------------------
# Public registry interface
# ---------------------------------------------------------------------------


class _TemplateRegistry:
    """In-memory store. 추후 JSON / DB 로 외부화 가능 (§32.5)."""

    def __init__(
        self,
        files: list[FileTemplate],
        commands: list[CommandTemplate],
    ) -> None:
        self._files = {t.template_id: t for t in files}
        self._commands = {t.template_id: t for t in commands}

    def get_file(self, template_id: str) -> Optional[FileTemplate]:
        return self._files.get(template_id)

    def get_command(self, template_id: str) -> Optional[CommandTemplate]:
        return self._commands.get(template_id)

    def all_files(self) -> list[FileTemplate]:
        return list(self._files.values())

    def all_commands(self) -> list[CommandTemplate]:
        return list(self._commands.values())


TEMPLATE_REGISTRY = _TemplateRegistry(_FILE_TEMPLATES, _COMMAND_TEMPLATES)


def get_file_template(template_id: str) -> Optional[FileTemplate]:
    return TEMPLATE_REGISTRY.get_file(template_id)


def get_command_template(template_id: str) -> Optional[CommandTemplate]:
    return TEMPLATE_REGISTRY.get_command(template_id)
